name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: '*/6 * * * *' #every 10 minutes
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: Ping www.zkea.net
      run: Web.Ping --host http://www.zkea.net
    - name: Ping scf
      run: Web.Ping --host https://service-laqz8pd5-1312133742.bj.apigw.tencentcs.com/release/SCFOnedriveIndex/
    - name: Ping bookmark
      run: Web.Ping --host https://lzs.azurewebsites.net/
